// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPejul5mww9qpJvqOAVvPU90cve7eQetw',
    appId: '1:47586903688:web:32cddf85cee3c99a16413d',
    messagingSenderId: '47586903688',
    projectId: 'locofest-c8d83',
    authDomain: 'locofest-c8d83.firebaseapp.com',
    storageBucket: 'locofest-c8d83.firebasestorage.app',
    measurementId: 'G-SMQ8VMMP9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc1hS-df-H_-njm1bUyOlerpRqL3qMxGM',
    appId: '1:47586903688:android:f14604e1b3abc4dd16413d',
    messagingSenderId: '47586903688',
    projectId: 'locofest-c8d83',
    storageBucket: 'locofest-c8d83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxofgA0TO5M9ENxjPIwQmUqWNTxuJ_fuE',
    appId: '1:47586903688:ios:12f2532783e1712e16413d',
    messagingSenderId: '47586903688',
    projectId: 'locofest-c8d83',
    storageBucket: 'locofest-c8d83.firebasestorage.app',
    iosBundleId: 'com.example.locofest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxofgA0TO5M9ENxjPIwQmUqWNTxuJ_fuE',
    appId: '1:47586903688:ios:12f2532783e1712e16413d',
    messagingSenderId: '47586903688',
    projectId: 'locofest-c8d83',
    storageBucket: 'locofest-c8d83.firebasestorage.app',
    iosBundleId: 'com.example.locofest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPejul5mww9qpJvqOAVvPU90cve7eQetw',
    appId: '1:47586903688:web:37a03bd579987a4616413d',
    messagingSenderId: '47586903688',
    projectId: 'locofest-c8d83',
    authDomain: 'locofest-c8d83.firebaseapp.com',
    storageBucket: 'locofest-c8d83.firebasestorage.app',
    measurementId: 'G-F3JVNV4RGM',
  );
}
